name       : haskell-split
version    : 0.2.3.3
release    : 5
source     :
    - https://hackage.haskell.org/package/split-0.2.3.3/split-0.2.3.3.tar.gz : 1dcd674f7c5f276f33300f5fd59e49d1ac6fc92ae949fd06a0f6d3e9d9ac1413
license    : BSD-3-Clause
component  : programming.haskell
summary    : A collection of various methods for splitting lists into parts, akin
    to the "split" function found in several mainstream languages.
description: |
    A collection of various methods for splitting lists into parts, akin to the "split" function found in several mainstream languages.
builddeps  :
    - ghc
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
