name       : haskell-split
version    : 0.2.3.1
release    : 2
source     :
    - http://hackage.haskell.org/package/split-0.2.3.1/split-0.2.3.1.tar.gz : 7615b60adee20c19ddafd9d74456e8fe8e4274e2c676a5e858511b664205c688
license    : BSD-3-Clause
component  : programming.haskell
summary    : A collection of various methods for splitting lists into parts, akin
    to the "split" function found in several mainstream languages.
description: |
    A collection of various methods for splitting lists into parts, akin to the "split" function found in several mainstream languages.
builddeps  :
    - ghc
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
