name       : haskell-split
version    : 0.2.3.4
release    : 6
source     :
    - https://hackage.haskell.org/package/split-0.2.3.4/split-0.2.3.4.tar.gz : 271fe5104c9f40034aa9a1aad6269bcecc9454bc5a57c247e69e17de996c1f2a
license    : BSD-3-Clause
component  : programming.haskell
summary    : A collection of various methods for splitting lists into parts, akin to the "split" function found in several mainstream languages.
description: |
    A collection of various methods for splitting lists into parts, akin to the "split" function found in several mainstream languages.
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
