name       : haskell-split
version    : 0.2.3.1
release    : 1
source     :
    - http://hackage.haskell.org/package/split-0.2.3.1/split-0.2.3.1.tar.gz : 7615b60adee20c19ddafd9d74456e8fe8e4274e2c676a5e858511b664205c688
license    : BSD-3-Clause
component  : programming
summary    : A collection of various methods for splitting lists into parts, akin to the "split" function found in several mainstream languages.
description: |
    A collection of various methods for splitting lists into parts, akin to the "split" function found in several mainstream languages.
builddeps  :
    - ghc
setup      : |
    ghc -threaded --make Setup
    ./Setup configure --enable-shared \
                      --prefix=/usr \
                      --docdir="/usr/share/doc/\$compiler/\$pkgid" \
                      --libdir=/usr/lib64 \
                      --libsubdir="\$compiler/\$pkgid" \
                      --datadir=/usr/share \
                      --sysconfdir=/etc
build      : |
    ./Setup build
install    : |
    export GHCV=`readlink /usr/bin/ghc`
    ./Setup copy --destdir=$installdir
    ./Setup register --gen-pkg-config
    install -D -m 00644 split-$version.conf $installdir/usr/lib64/$GHCV/package.conf.d/split-$version.conf
    rm -f $installdir/usr/lib64/$GHCV/split-$version/*.a
